name: Build LuCI IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev bc flex bison zstd

      - name: Download OpenWrt SDK
        run: |
          wget -O sdk.tar.zst https://downloads.openwrt.org/releases/25.12.0/targets/rockchip/armv8/openwrt-sdk-25.12.0-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf sdk.tar.zst || tar --zstd -xf sdk.tar.zst
          mv openwrt-sdk-* sdk

      - name: Add Package
        run: |
          # 1. 在 SDK 中创建插件目录
          mkdir -p sdk/package/luci-app-autoredial
          
          # 2. 将仓库根目录下的所有文件复制到 SDK 插件目录中
          # 解释：因为你的代码在根目录，所以我们要复制当前目录(.)的内容
          # 排除 sdk 文件夹本身，防止递归复制
          find . -maxdepth 1 ! -name '.' ! -name 'sdk' ! -name '.git' ! -name '.github' -exec cp -r {} sdk/package/luci-app-autoredial/ \;

      - name: Compile
        working-directory: ./sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make package/luci-app-autoredial/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-rockchip-ipk
          # 使用通配符 ** 自动查找生成的 ipk 文件
          path: sdk/bin/**/*.ipk
