name: Build LuCI IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          sudo apt update
          # 修复：添加 python3-elftools 解决 "Please install the Python3 elftools module" 错误
          sudo apt install -y build-essential libncurses-dev bc flex bison zstd python3-elftools

      - name: Download OpenWrt SDK
        run: |
          wget -O sdk.tar.zst https://downloads.openwrt.org/releases/25.12.0/targets/rockchip/armv8/openwrt-sdk-25.12.0-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf sdk.tar.zst || tar --zstd -xf sdk.tar.zst
          mv openwrt-sdk-* sdk

      - name: Add Package
        run: |
          mkdir -p sdk/package/luci-app-autoredial
          # 将根目录下的代码复制到 SDK 中
          find . -maxdepth 1 ! -name '.' ! -name 'sdk' ! -name '.git' ! -name '.github' -exec cp -r {} sdk/package/luci-app-autoredial/ \;

      - name: Compile
        working-directory: ./sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # 生成默认配置，防止触发 menuconfig
          make defconfig
          
          make package/luci-app-autoredial/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-rockchip-ipk
          path: sdk/bin/**/*.ipk
